# Site settings
site: Blog
title: Bhaskar's Blog 
keywords: bhaskarvilles, blog
description: >-
  Blog - A simple Blog
lang: en-US
timezone:  India/Kolkata
repo: https://github.com/onepase/Ephesus # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Bhaskar
  bio: Computer Engineer, <br> Founder @w3 technology <br> Open Source /#linux
  picture: assets/images/profile.jpg 
  github: bhaskarvilles # github username
  twitter: bhaskarvilles # twitter username
  facebook: bhaskarvilles # facebook username
  instagram: bhaskarvilles # instagram username
  youtube: https://www.youtube.com/channel/fuckologyunofficial # youtube username
  linkedin: bhaskarvilles # linkedin username
  email: bhaskarvilles@icloud.com # email adress


# URL settings
url: "bhaskarvilles.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
